import type { ShopCategory } from '@/types';
/**
 * Mock 分類資料（來自真實 API）
 */
export const mockCategories: ShopCategory[] = [
  {
    id: 1,
    name: '電子產品',
    description: '各類電子產品及3C商品',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 3,
        name: '手機',
        description: '各品牌智慧型手機',
        active: true,
        productCount: 0,
      },
      {
        id: 4,
        name: '筆記型電腦',
        description: '各品牌筆電',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-11T04:26:56.931545',
    updatedAt: '2025-12-11T04:26:56.931556',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 2,
    name: '服飾',
    description: '男女服飾及配件',
    parentId: null,
    parentName: null,
    children: [],
    active: true,
    createdAt: '2025-12-11T04:27:31.362122',
    updatedAt: '2025-12-11T04:27:31.362136',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 5,
    name: '生日派對',
    description: '各式生日派對氣球商品，打造難忘的生日慶典',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 10,
        name: '數字氣球組',
        description: '各種尺寸與顏色的生日數字氣球組合',
        active: true,
        productCount: 3,
      },
      {
        id: 11,
        name: '卡通主題組',
        description: '熱門卡通角色主題氣球套裝',
        active: true,
        productCount: 3,
      },
      {
        id: 12,
        name: '生日氣球套裝',
        description: '完整生日派對氣球佈置套組',
        active: true,
        productCount: 0,
      },
      {
        id: 13,
        name: '生日佈置配件',
        description: '生日派對氣球佈置周邊配件',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-17T05:29:07.027475',
    updatedAt: '2025-12-17T05:29:07.027475',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 6,
    name: '婚禮求婚',
    description: '浪漫婚禮與求婚場景氣球佈置商品',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 14,
        name: '婚禮氣球組',
        description: '典雅浪漫婚禮場景氣球套裝',
        active: true,
        productCount: 2,
      },
      {
        id: 15,
        name: '求婚氣球套裝',
        description: '浪漫求婚場景專用氣球組合',
        active: true,
        productCount: 3,
      },
      {
        id: 16,
        name: '浪漫愛心球',
        description: '各式愛心造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 17,
        name: '客製化文字球',
        description: '可訂製姓名與祝福語氣球',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-17T05:29:07.027475',
    updatedAt: '2025-12-17T05:29:07.027475',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 7,
    name: '節慶活動',
    description: '節日慶典主題氣球，為節日增添歡樂氣氛',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 18,
        name: '聖誕主題',
        description: '聖誕節慶氣球佈置商品',
        active: true,
        productCount: 0,
      },
      {
        id: 19,
        name: '新年開運',
        description: '農曆新年與跨年慶典氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 20,
        name: '萬聖節',
        description: '萬聖節派對主題氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 21,
        name: '情人節',
        description: '情人節浪漫氣球商品',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-17T05:29:07.027475',
    updatedAt: '2025-12-17T05:29:07.027475',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 8,
    name: '企業商用',
    description: '企業活動、開幕典禮專業氣球方案',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 22,
        name: '開幕氣球',
        description: '店面開幕、剪綵活動氣球',
        active: true,
        productCount: 3,
      },
      {
        id: 23,
        name: '客製化印刷球',
        description: '企業 LOGO 與文字客製印刷氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 24,
        name: '大型廣告球',
        description: '戶外展示用大型充氣氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 25,
        name: '企業活動套組',
        description: '企業尾牙、記者會氣球套裝',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-17T05:29:07.027475',
    updatedAt: '2025-12-17T05:29:07.027475',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 9,
    name: '基礎耗材',
    description: '氣球佈置必備基礎材料與工具',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 26,
        name: '素色乳膠球',
        description: '各色基礎乳膠氣球',
        active: true,
        productCount: 3,
      },
      {
        id: 27,
        name: '充氣工具',
        description: '手動打氣筒、電動打氣機、氦氣罐',
        active: true,
        productCount: 3,
      },
      {
        id: 28,
        name: '固定配件',
        description: '氣球固定器、配重、膠帶',
        active: true,
        productCount: 0,
      },
      {
        id: 29,
        name: '裝飾耗材',
        description: '緞帶、亮片、裝飾貼紙',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2025-12-17T05:29:07.027475',
    updatedAt: '2025-12-17T05:29:07.027475',
    isTopLevel: true,
    productCount: 0,
  },
];
