import type { ShopCategory } from '@/types';
/**
 * Mock 分類資料（來自真實 API）
 */
export const mockCategories: ShopCategory[] = [
  {
    id: 1,
    name: '主題佈置',
    description: '依場合與風格主題打造的專屬氣球佈置',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 8,
        name: '畢業佈置',
        description: '畢業典禮、謝師宴專屬氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 9,
        name: '生日佈置',
        description: '各年齡生日派對氣球佈置服務',
        active: true,
        productCount: 0,
      },
      {
        id: 10,
        name: '開幕佈置',
        description: '店面開幕、新店落成氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 11,
        name: '展演佈置',
        description: '展覽、演出、發表會場地氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 12,
        name: '背板佈置',
        description: '活動背板、拍照牆氣球造型設計',
        active: true,
        productCount: 0,
      },
      {
        id: 13,
        name: '森林系佈置',
        description: '自然森林風格氣球佈置，綠意盎然',
        active: true,
        productCount: 0,
      },
      {
        id: 14,
        name: '海洋系佈置',
        description: '海洋風格氣球佈置，清新活潑',
        active: true,
        productCount: 0,
      },
      {
        id: 15,
        name: '童話系佈置',
        description: '童話故事風格氣球佈置，充滿奇幻色彩',
        active: true,
        productCount: 0,
      },
      {
        id: 16,
        name: '甜美系佈置',
        description: '粉嫩甜美風格氣球佈置，少女心滿滿',
        active: true,
        productCount: 0,
      },
      {
        id: 17,
        name: '夢幻系佈置',
        description: '夢幻唯美風格氣球佈置，打造如詩如畫的場景',
        active: true,
        productCount: 0,
      },
      {
        id: 18,
        name: '其他佈置',
        description: '其他風格主題氣球佈置',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 2,
    name: '造型氣球',
    description: '各式造型氣球，手工製作充滿趣味與創意',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 19,
        name: '動物造型',
        description: '各種可愛動物造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 20,
        name: '公主系列',
        description: '夢幻公主風格造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 21,
        name: '手拿棒系列',
        description: '適合拍照的手持造型氣球棒',
        active: true,
        productCount: 0,
      },
      {
        id: 22,
        name: '武器系列',
        description: '劍、盾、弓箭等武器造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 23,
        name: '配件系列',
        description: '帽子、眼鏡、包包等配件造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 24,
        name: '卡通造型',
        description: '熱門卡通角色造型氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 25,
        name: '四泡結手環系列',
        description: '四泡結工法製作的氣球手環',
        active: true,
        productCount: 0,
      },
      {
        id: 26,
        name: '編織系列',
        description: '氣球編織工藝造型商品',
        active: true,
        productCount: 0,
      },
      {
        id: 54,
        name: '花朵系列',
        description: '花朵造型氣球，適合送禮與佈置點綴',
        active: true,
        productCount: 0,
      },
      {
        id: 27,
        name: '其他系列',
        description: '其他創意造型氣球',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 3,
    name: '節慶佈置',
    description: '各大節日慶典主題氣球佈置，為節日增添喜慶氣氛',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 28,
        name: '聖誕節佈置',
        description: '聖誕節慶氣球佈置，營造溫馨節日氛圍',
        active: true,
        productCount: 0,
      },
      {
        id: 29,
        name: '萬聖節佈置',
        description: '萬聖節派對主題氣球佈置，趣味十足',
        active: true,
        productCount: 0,
      },
      {
        id: 30,
        name: '新年佈置',
        description: '農曆新年與跨年慶典氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 31,
        name: '情人節佈置',
        description: '情人節浪漫氣球佈置，傳遞愛意',
        active: true,
        productCount: 0,
      },
      {
        id: 32,
        name: '母親節佈置',
        description: '母親節感恩氣球佈置，表達對媽媽的愛',
        active: true,
        productCount: 0,
      },
      {
        id: 33,
        name: '父親節佈置',
        description: '父親節氣球佈置，感謝爸爸的付出',
        active: true,
        productCount: 0,
      },
      {
        id: 34,
        name: '其他節慶佈置',
        description: '其他節日慶典氣球佈置',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 4,
    name: '依年齡佈置',
    description: '依壽星年齡量身打造的專屬氣球佈置',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 35,
        name: '0 歲佈置',
        description: '彌月、百日嬰兒專屬氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 36,
        name: '1 歲佈置',
        description: '寶寶抓周、滿周歲慶典氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 37,
        name: '2~6 歲佈置',
        description: '幼兒生日派對卡通主題氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 38,
        name: '7~12 歲佈置',
        description: '兒童生日派對活潑主題氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 39,
        name: '13~18 歲佈置',
        description: '青少年生日派對時尚主題氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 40,
        name: '19+ 歲佈置',
        description: '成人生日派對精緻主題氣球佈置',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 5,
    name: '婚禮求婚',
    description: '浪漫婚禮與求婚場景氣球佈置，打造永生難忘的幸福時刻',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 41,
        name: '婚禮佈置',
        description: '典雅浪漫婚禮場景整體氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 42,
        name: '求婚佈置',
        description: '浪漫驚喜求婚場景氣球佈置',
        active: true,
        productCount: 0,
      },
      {
        id: 43,
        name: '客製化文字球',
        description: '可訂製姓名、日期與祝福語的專屬文字氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 44,
        name: '其他婚禮求婚佈置',
        description: '其他婚禮求婚相關氣球佈置',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 6,
    name: '企業商用',
    description: '企業活動、開幕典禮等商業場合專業氣球佈置方案',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 45,
        name: '爆破氣球佈置',
        description: '活動開幕、頒獎典禮爆破氣球裝置',
        active: true,
        productCount: 0,
      },
      {
        id: 46,
        name: '氣球柱',
        description: '活動入口、舞台兩側氣球柱造型',
        active: true,
        productCount: 0,
      },
      {
        id: 47,
        name: '氣球牆',
        description: '大型氣球牆佈置，適合拍照打卡',
        active: true,
        productCount: 0,
      },
      {
        id: 60,
        name: '氣球拱門',
        description: '活動入口、舞台前方大型氣球拱門造型',
        active: true,
        productCount: 0,
      },
      {
        id: 48,
        name: '其他企業商用佈置',
        description: '其他企業商業場合氣球佈置',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 7,
    name: '基礎耗材',
    description: '氣球佈置必備基礎材料與工具',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 49,
        name: '鋁箔氣球',
        description: '各式造型鋁箔氣球，持久耐用',
        active: true,
        productCount: 0,
      },
      {
        id: 50,
        name: '長條乳膠氣球',
        description: '造型塑形用長條乳膠氣球',
        active: true,
        productCount: 0,
      },
      {
        id: 51,
        name: '圓型乳膠氣球',
        description: '各色圓形乳膠氣球，佈置必備',
        active: true,
        productCount: 0,
      },
      {
        id: 52,
        name: '打氣筒',
        description: '手動打氣筒、電動打氣機、氦氣罐',
        active: true,
        productCount: 0,
      },
      {
        id: 53,
        name: '其他基礎耗材',
        description: '固定配件、緞帶、裝飾貼紙等佈置耗材',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-03T00:00:00.000000',
    updatedAt: '2026-03-03T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
  {
    id: 55,
    name: '空飄系列',
    description: '氦氣充填空飄氣球，依材質分類，適合各式派對與場地佈置點綴',
    parentId: null,
    parentName: null,
    children: [
      {
        id: 56,
        name: '乳膠氣球',
        description:
          '價格親民、顏色多樣，提供標準色、珍珠色、金屬色及大理石紋，飄浮時間約 8–12 小時',
        active: true,
        productCount: 0,
      },
      {
        id: 57,
        name: '鋁箔氣球',
        description:
          '造型多變（數字、字母、卡通、愛心、星星），自封口設計密封性佳，飄浮時間約 3–7 天以上',
        active: true,
        productCount: 0,
      },
      {
        id: 58,
        name: '泡泡球',
        description:
          '透明高彈性 PVC 材質，可內含羽毛、紙花或小氣球，常搭配客製化割字貼紙，外觀精緻',
        active: true,
        productCount: 0,
      },
      {
        id: 59,
        name: '特殊造型鋁箔',
        description:
          '立體造型鋁箔氣球（Orbz、DMZ、CBZ 等），外型特殊圓潤，適合現代感或奢華感婚禮與派對',
        active: true,
        productCount: 0,
      },
    ],
    active: true,
    createdAt: '2026-03-07T00:00:00.000000',
    updatedAt: '2026-03-07T00:00:00.000000',
    isTopLevel: true,
    productCount: 0,
  },
];
