import type { Order } from '@/types';

// 靜態模式示例訂單資料（用於 GitHub Pages 展示）
export function getMockOrder(orderId: number): Order {
  const mockOrders: Record<number, Order> = {
    1: {
      id: 1,
      orderNumber: 'DEMO20240101001',
      status: 'ORDER_DELIVERED',
      totalAmount: 2950,
      shippingFee: 150,
      paymentMethod: 'CREDIT_CARD',
      recipientName: '張小明',
      recipientPhone: '0912-345-678',
      recipientEmail: 'demo@example.com',
      city: '台北市',
      district: '信義區',
      postalCode: '110',
      addressLine: '信義路五段7號',
      note: '請在平日上班時間送達',
      createdAt: new Date('2024-01-01T10:30:00').toISOString(),
      updatedAt: new Date('2024-01-01T10:30:00').toISOString(),
      paidAt: new Date('2024-01-01T10:32:00').toISOString(),
      shippedAt: new Date('2024-01-02T14:00:00').toISOString(),
      completedAt: new Date('2024-01-03T10:00:00').toISOString(),
      items: [
        {
          id: 1,
          productId: 1,
          productName: '經典桌遊組合',
          productImage: '/images/products/product1.jpg',
          quantity: 2,
          unitPrice: 1200,
          subtotal: 2400,
        },
        {
          id: 2,
          productId: 2,
          productName: '派對道具包',
          productImage: '/images/products/product2.jpg',
          quantity: 1,
          unitPrice: 400,
          subtotal: 400,
        },
      ],
    },
    2: {
      id: 2,
      orderNumber: 'DEMO20240102002',
      status: 'ORDER_SHIPPED',
      totalAmount: 1650,
      shippingFee: 150,
      paymentMethod: 'CASH_ON_DELIVERY',
      recipientName: '李小華',
      recipientPhone: '0923-456-789',
      recipientEmail: 'demo2@example.com',
      city: '新北市',
      district: '板橋區',
      postalCode: '220',
      addressLine: '文化路一段188號',
      note: null,
      createdAt: new Date('2024-01-02T14:20:00').toISOString(),
      updatedAt: new Date('2024-01-02T14:20:00').toISOString(),
      paidAt: null,
      shippedAt: new Date('2024-01-03T09:00:00').toISOString(),
      completedAt: null,
      items: [
        {
          id: 3,
          productId: 3,
          productName: '歡樂氣球組',
          productImage: '/images/products/product3.jpg',
          quantity: 3,
          unitPrice: 500,
          subtotal: 1500,
        },
      ],
    },
    3: {
      id: 3,
      orderNumber: 'DEMO20240103003',
      status: 'ORDER_PENDING',
      totalAmount: 3150,
      shippingFee: 150,
      paymentMethod: 'CREDIT_CARD',
      recipientName: '王大明',
      recipientPhone: '0934-567-890',
      recipientEmail: 'demo3@example.com',
      city: '台中市',
      district: '西屯區',
      postalCode: '407',
      addressLine: '台灣大道三段99號',
      note: '希望使用精美包裝',
      createdAt: new Date('2024-01-03T09:15:00').toISOString(),
      updatedAt: new Date('2024-01-03T09:15:00').toISOString(),
      paidAt: null,
      shippedAt: null,
      completedAt: null,
      items: [
        {
          id: 4,
          productId: 4,
          productName: '豪華派對組合',
          productImage: '/images/products/product4.jpg',
          quantity: 1,
          unitPrice: 3000,
          subtotal: 3000,
        },
      ],
    },
  };

  return (
    mockOrders[orderId] || {
      id: orderId,
      orderNumber: `DEMO${orderId}`,
      status: 'ORDER_PENDING',
      totalAmount: 1500,
      shippingFee: 150,
      paymentMethod: 'CREDIT_CARD',
      recipientName: '示例用戶',
      recipientPhone: '0912-345-678',
      recipientEmail: 'demo@example.com',
      city: '台北市',
      district: '中正區',
      postalCode: '100',
      addressLine: '示例路1號',
      note: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      paidAt: null,
      shippedAt: null,
      completedAt: null,
      items: [
        {
          id: 1,
          productId: 1,
          productName: '示例商品',
          productImage: null,
          quantity: 1,
          unitPrice: 1350,
          subtotal: 1350,
        },
      ],
    }
  );
}
